### ISSUE TITLE
Queue limit research doesn't work

### ISSUE THREAD

**Issue by Avolendi** [Muffinman/InfiniteConflict#66]
Researched queue limit 4, however neither in the building queue nor the training queue (currently only available ones to me) can I use the 4th slot.

**Comment by Muffinman** [comment]
This one was fixed very recently. Could you try researching QL5 and confirm if this works?

**Comment by Muffinman** [comment]
Going to close this because I just tested again and it's working for me. Feel free to request re-open if still an issue for you.
